section .rodata

global _binary_CharisSIL_BoldItalic_cff
global _binary_CharisSIL_BoldItalic_cff_start
global _binary_CharisSIL_BoldItalic_cff_end
global _binary_CharisSIL_BoldItalic_cff_size
_binary_CharisSIL_BoldItalic_cff:
_binary_CharisSIL_BoldItalic_cff_start:
    db 0
_binary_CharisSIL_BoldItalic_cff_end:
_binary_CharisSIL_BoldItalic_cff_size: dq 0

global _binary_CharisSIL_Bold_cff
global _binary_CharisSIL_Bold_cff_start
global _binary_CharisSIL_Bold_cff_end
global _binary_CharisSIL_Bold_cff_size
_binary_CharisSIL_Bold_cff:
_binary_CharisSIL_Bold_cff_start:
    db 0
_binary_CharisSIL_Bold_cff_end:
_binary_CharisSIL_Bold_cff_size: dq 0

global _binary_CharisSIL_Italic_cff
global _binary_CharisSIL_Italic_cff_start
global _binary_CharisSIL_Italic_cff_end
global _binary_CharisSIL_Italic_cff_size
_binary_CharisSIL_Italic_cff:
_binary_CharisSIL_Italic_cff_start:
    db 0
_binary_CharisSIL_Italic_cff_end:
_binary_CharisSIL_Italic_cff_size: dq 0

global _binary_CharisSIL_cff
global _binary_CharisSIL_cff_start
global _binary_CharisSIL_cff_end
global _binary_CharisSIL_cff_size
_binary_CharisSIL_cff:
_binary_CharisSIL_cff_start:
    db 0
_binary_CharisSIL_cff_end:
_binary_CharisSIL_cff_size: dq 0

global _binary_Dingbats_cff
global _binary_Dingbats_cff_start
global _binary_Dingbats_cff_end
global _binary_Dingbats_cff_size
_binary_Dingbats_cff:
_binary_Dingbats_cff_start:
    db 0
_binary_Dingbats_cff_end:
_binary_Dingbats_cff_size: dq 0

global _binary_DroidSansFallbackFull_ttf
global _binary_DroidSansFallbackFull_ttf_start
global _binary_DroidSansFallbackFull_ttf_end
global _binary_DroidSansFallbackFull_ttf_size
_binary_DroidSansFallbackFull_ttf:
_binary_DroidSansFallbackFull_ttf_start:
    incbin "mupdf/resources/fonts/droid/DroidSansFallbackFull.ttf"
_binary_DroidSansFallbackFull_ttf_end:
_binary_DroidSansFallbackFull_ttf_size: dq _binary_DroidSansFallbackFull_ttf_end - _binary_DroidSansFallbackFull_ttf_start

global _binary_DroidSansFallback_ttf
global _binary_DroidSansFallback_ttf_start
global _binary_DroidSansFallback_ttf_end
global _binary_DroidSansFallback_ttf_size
_binary_DroidSansFallback_ttf:
_binary_DroidSansFallback_ttf_start:
    db 0
_binary_DroidSansFallback_ttf_end:
_binary_DroidSansFallback_ttf_size: dq 0

global _binary_NimbusMonoPS_BoldItalic_cff
global _binary_NimbusMonoPS_BoldItalic_cff_start
global _binary_NimbusMonoPS_BoldItalic_cff_end
global _binary_NimbusMonoPS_BoldItalic_cff_size
_binary_NimbusMonoPS_BoldItalic_cff:
_binary_NimbusMonoPS_BoldItalic_cff_start:
    db 0
_binary_NimbusMonoPS_BoldItalic_cff_end:
_binary_NimbusMonoPS_BoldItalic_cff_size: dq 0

global _binary_NimbusMonoPS_Bold_cff
global _binary_NimbusMonoPS_Bold_cff_start
global _binary_NimbusMonoPS_Bold_cff_end
global _binary_NimbusMonoPS_Bold_cff_size
_binary_NimbusMonoPS_Bold_cff:
_binary_NimbusMonoPS_Bold_cff_start:
    db 0
_binary_NimbusMonoPS_Bold_cff_end:
_binary_NimbusMonoPS_Bold_cff_size: dq 0

global _binary_NimbusMonoPS_Italic_cff
global _binary_NimbusMonoPS_Italic_cff_start
global _binary_NimbusMonoPS_Italic_cff_end
global _binary_NimbusMonoPS_Italic_cff_size
_binary_NimbusMonoPS_Italic_cff:
_binary_NimbusMonoPS_Italic_cff_start:
    db 0
_binary_NimbusMonoPS_Italic_cff_end:
_binary_NimbusMonoPS_Italic_cff_size: dq 0

global _binary_NimbusMonoPS_Regular_cff
global _binary_NimbusMonoPS_Regular_cff_start
global _binary_NimbusMonoPS_Regular_cff_end
global _binary_NimbusMonoPS_Regular_cff_size
_binary_NimbusMonoPS_Regular_cff:
_binary_NimbusMonoPS_Regular_cff_start:
    db 0
_binary_NimbusMonoPS_Regular_cff_end:
_binary_NimbusMonoPS_Regular_cff_size: dq 0

global _binary_NimbusRoman_BoldItalic_cff
global _binary_NimbusRoman_BoldItalic_cff_start
global _binary_NimbusRoman_BoldItalic_cff_end
global _binary_NimbusRoman_BoldItalic_cff_size
_binary_NimbusRoman_BoldItalic_cff:
_binary_NimbusRoman_BoldItalic_cff_start:
    db 0
_binary_NimbusRoman_BoldItalic_cff_end:
_binary_NimbusRoman_BoldItalic_cff_size: dq 0

global _binary_NimbusRoman_Bold_cff
global _binary_NimbusRoman_Bold_cff_start
global _binary_NimbusRoman_Bold_cff_end
global _binary_NimbusRoman_Bold_cff_size
_binary_NimbusRoman_Bold_cff:
_binary_NimbusRoman_Bold_cff_start:
    db 0
_binary_NimbusRoman_Bold_cff_end:
_binary_NimbusRoman_Bold_cff_size: dq 0

global _binary_NimbusRoman_Italic_cff
global _binary_NimbusRoman_Italic_cff_start
global _binary_NimbusRoman_Italic_cff_end
global _binary_NimbusRoman_Italic_cff_size
_binary_NimbusRoman_Italic_cff:
_binary_NimbusRoman_Italic_cff_start:
    db 0
_binary_NimbusRoman_Italic_cff_end:
_binary_NimbusRoman_Italic_cff_size: dq 0

global _binary_NimbusRoman_Regular_cff
global _binary_NimbusRoman_Regular_cff_start
global _binary_NimbusRoman_Regular_cff_end
global _binary_NimbusRoman_Regular_cff_size
_binary_NimbusRoman_Regular_cff:
_binary_NimbusRoman_Regular_cff_start:
    db 0
_binary_NimbusRoman_Regular_cff_end:
_binary_NimbusRoman_Regular_cff_size: dq 0

global _binary_NimbusSans_BoldItalic_cff
global _binary_NimbusSans_BoldItalic_cff_start
global _binary_NimbusSans_BoldItalic_cff_end
global _binary_NimbusSans_BoldItalic_cff_size
_binary_NimbusSans_BoldItalic_cff:
_binary_NimbusSans_BoldItalic_cff_start:
    db 0
_binary_NimbusSans_BoldItalic_cff_end:
_binary_NimbusSans_BoldItalic_cff_size: dq 0

global _binary_NimbusSans_Bold_cff
global _binary_NimbusSans_Bold_cff_start
global _binary_NimbusSans_Bold_cff_end
global _binary_NimbusSans_Bold_cff_size
_binary_NimbusSans_Bold_cff:
_binary_NimbusSans_Bold_cff_start:
    db 0
_binary_NimbusSans_Bold_cff_end:
_binary_NimbusSans_Bold_cff_size: dq 0

global _binary_NimbusSans_Italic_cff
global _binary_NimbusSans_Italic_cff_start
global _binary_NimbusSans_Italic_cff_end
global _binary_NimbusSans_Italic_cff_size
_binary_NimbusSans_Italic_cff:
_binary_NimbusSans_Italic_cff_start:
    db 0
_binary_NimbusSans_Italic_cff_end:
_binary_NimbusSans_Italic_cff_size: dq 0

global _binary_NimbusSans_Regular_cff
global _binary_NimbusSans_Regular_cff_start
global _binary_NimbusSans_Regular_cff_end
global _binary_NimbusSans_Regular_cff_size
_binary_NimbusSans_Regular_cff:
_binary_NimbusSans_Regular_cff_start:
    db 0
_binary_NimbusSans_Regular_cff_end:
_binary_NimbusSans_Regular_cff_size: dq 0

global _binary_NotoEmoji_Regular_ttf
global _binary_NotoEmoji_Regular_ttf_start
global _binary_NotoEmoji_Regular_ttf_end
global _binary_NotoEmoji_Regular_ttf_size
_binary_NotoEmoji_Regular_ttf:
_binary_NotoEmoji_Regular_ttf_start:
    incbin "mupdf/resources/fonts/noto/NotoEmoji-Regular.ttf"
_binary_NotoEmoji_Regular_ttf_end:
_binary_NotoEmoji_Regular_ttf_size: dq _binary_NotoEmoji_Regular_ttf_end - _binary_NotoEmoji_Regular_ttf_start

global _binary_NotoMusic_Regular_otf
global _binary_NotoMusic_Regular_otf_start
global _binary_NotoMusic_Regular_otf_end
global _binary_NotoMusic_Regular_otf_size
_binary_NotoMusic_Regular_otf:
_binary_NotoMusic_Regular_otf_start:
    db 0
_binary_NotoMusic_Regular_otf_end:
_binary_NotoMusic_Regular_otf_size: dq 0

global _binary_NotoNaskhArabic_Regular_otf
global _binary_NotoNaskhArabic_Regular_otf_start
global _binary_NotoNaskhArabic_Regular_otf_end
global _binary_NotoNaskhArabic_Regular_otf_size
_binary_NotoNaskhArabic_Regular_otf:
_binary_NotoNaskhArabic_Regular_otf_start:
    db 0
_binary_NotoNaskhArabic_Regular_otf_end:
_binary_NotoNaskhArabic_Regular_otf_size: dq 0

global _binary_NotoNastaliqUrdu_Regular_otf
global _binary_NotoNastaliqUrdu_Regular_otf_start
global _binary_NotoNastaliqUrdu_Regular_otf_end
global _binary_NotoNastaliqUrdu_Regular_otf_size
_binary_NotoNastaliqUrdu_Regular_otf:
_binary_NotoNastaliqUrdu_Regular_otf_start:
    db 0
_binary_NotoNastaliqUrdu_Regular_otf_end:
_binary_NotoNastaliqUrdu_Regular_otf_size: dq 0

global _binary_NotoSansAdlam_Regular_otf
global _binary_NotoSansAdlam_Regular_otf_start
global _binary_NotoSansAdlam_Regular_otf_end
global _binary_NotoSansAdlam_Regular_otf_size
_binary_NotoSansAdlam_Regular_otf:
_binary_NotoSansAdlam_Regular_otf_start:
    db 0
_binary_NotoSansAdlam_Regular_otf_end:
_binary_NotoSansAdlam_Regular_otf_size: dq 0

global _binary_NotoSansAnatolianHieroglyphs_Regular_otf
global _binary_NotoSansAnatolianHieroglyphs_Regular_otf_start
global _binary_NotoSansAnatolianHieroglyphs_Regular_otf_end
global _binary_NotoSansAnatolianHieroglyphs_Regular_otf_size
_binary_NotoSansAnatolianHieroglyphs_Regular_otf:
_binary_NotoSansAnatolianHieroglyphs_Regular_otf_start:
    db 0
_binary_NotoSansAnatolianHieroglyphs_Regular_otf_end:
_binary_NotoSansAnatolianHieroglyphs_Regular_otf_size: dq 0

global _binary_NotoSansAvestan_Regular_otf
global _binary_NotoSansAvestan_Regular_otf_start
global _binary_NotoSansAvestan_Regular_otf_end
global _binary_NotoSansAvestan_Regular_otf_size
_binary_NotoSansAvestan_Regular_otf:
_binary_NotoSansAvestan_Regular_otf_start:
    db 0
_binary_NotoSansAvestan_Regular_otf_end:
_binary_NotoSansAvestan_Regular_otf_size: dq 0

global _binary_NotoSansBamum_Regular_otf
global _binary_NotoSansBamum_Regular_otf_start
global _binary_NotoSansBamum_Regular_otf_end
global _binary_NotoSansBamum_Regular_otf_size
_binary_NotoSansBamum_Regular_otf:
_binary_NotoSansBamum_Regular_otf_start:
    db 0
_binary_NotoSansBamum_Regular_otf_end:
_binary_NotoSansBamum_Regular_otf_size: dq 0

global _binary_NotoSansBassaVah_Regular_otf
global _binary_NotoSansBassaVah_Regular_otf_start
global _binary_NotoSansBassaVah_Regular_otf_end
global _binary_NotoSansBassaVah_Regular_otf_size
_binary_NotoSansBassaVah_Regular_otf:
_binary_NotoSansBassaVah_Regular_otf_start:
    db 0
_binary_NotoSansBassaVah_Regular_otf_end:
_binary_NotoSansBassaVah_Regular_otf_size: dq 0

global _binary_NotoSansBatak_Regular_otf
global _binary_NotoSansBatak_Regular_otf_start
global _binary_NotoSansBatak_Regular_otf_end
global _binary_NotoSansBatak_Regular_otf_size
_binary_NotoSansBatak_Regular_otf:
_binary_NotoSansBatak_Regular_otf_start:
    db 0
_binary_NotoSansBatak_Regular_otf_end:
_binary_NotoSansBatak_Regular_otf_size: dq 0

global _binary_NotoSansBhaiksuki_Regular_otf
global _binary_NotoSansBhaiksuki_Regular_otf_start
global _binary_NotoSansBhaiksuki_Regular_otf_end
global _binary_NotoSansBhaiksuki_Regular_otf_size
_binary_NotoSansBhaiksuki_Regular_otf:
_binary_NotoSansBhaiksuki_Regular_otf_start:
    db 0
_binary_NotoSansBhaiksuki_Regular_otf_end:
_binary_NotoSansBhaiksuki_Regular_otf_size: dq 0

global _binary_NotoSansBrahmi_Regular_otf
global _binary_NotoSansBrahmi_Regular_otf_start
global _binary_NotoSansBrahmi_Regular_otf_end
global _binary_NotoSansBrahmi_Regular_otf_size
_binary_NotoSansBrahmi_Regular_otf:
_binary_NotoSansBrahmi_Regular_otf_start:
    db 0
_binary_NotoSansBrahmi_Regular_otf_end:
_binary_NotoSansBrahmi_Regular_otf_size: dq 0

global _binary_NotoSansBuginese_Regular_otf
global _binary_NotoSansBuginese_Regular_otf_start
global _binary_NotoSansBuginese_Regular_otf_end
global _binary_NotoSansBuginese_Regular_otf_size
_binary_NotoSansBuginese_Regular_otf:
_binary_NotoSansBuginese_Regular_otf_start:
    db 0
_binary_NotoSansBuginese_Regular_otf_end:
_binary_NotoSansBuginese_Regular_otf_size: dq 0

global _binary_NotoSansBuhid_Regular_otf
global _binary_NotoSansBuhid_Regular_otf_start
global _binary_NotoSansBuhid_Regular_otf_end
global _binary_NotoSansBuhid_Regular_otf_size
_binary_NotoSansBuhid_Regular_otf:
_binary_NotoSansBuhid_Regular_otf_start:
    db 0
_binary_NotoSansBuhid_Regular_otf_end:
_binary_NotoSansBuhid_Regular_otf_size: dq 0

global _binary_NotoSansCanadianAboriginal_Regular_otf
global _binary_NotoSansCanadianAboriginal_Regular_otf_start
global _binary_NotoSansCanadianAboriginal_Regular_otf_end
global _binary_NotoSansCanadianAboriginal_Regular_otf_size
_binary_NotoSansCanadianAboriginal_Regular_otf:
_binary_NotoSansCanadianAboriginal_Regular_otf_start:
    db 0
_binary_NotoSansCanadianAboriginal_Regular_otf_end:
_binary_NotoSansCanadianAboriginal_Regular_otf_size: dq 0

global _binary_NotoSansCarian_Regular_otf
global _binary_NotoSansCarian_Regular_otf_start
global _binary_NotoSansCarian_Regular_otf_end
global _binary_NotoSansCarian_Regular_otf_size
_binary_NotoSansCarian_Regular_otf:
_binary_NotoSansCarian_Regular_otf_start:
    db 0
_binary_NotoSansCarian_Regular_otf_end:
_binary_NotoSansCarian_Regular_otf_size: dq 0

global _binary_NotoSansCaucasianAlbanian_Regular_otf
global _binary_NotoSansCaucasianAlbanian_Regular_otf_start
global _binary_NotoSansCaucasianAlbanian_Regular_otf_end
global _binary_NotoSansCaucasianAlbanian_Regular_otf_size
_binary_NotoSansCaucasianAlbanian_Regular_otf:
_binary_NotoSansCaucasianAlbanian_Regular_otf_start:
    db 0
_binary_NotoSansCaucasianAlbanian_Regular_otf_end:
_binary_NotoSansCaucasianAlbanian_Regular_otf_size: dq 0

global _binary_NotoSansChakma_Regular_otf
global _binary_NotoSansChakma_Regular_otf_start
global _binary_NotoSansChakma_Regular_otf_end
global _binary_NotoSansChakma_Regular_otf_size
_binary_NotoSansChakma_Regular_otf:
_binary_NotoSansChakma_Regular_otf_start:
    db 0
_binary_NotoSansChakma_Regular_otf_end:
_binary_NotoSansChakma_Regular_otf_size: dq 0

global _binary_NotoSansCham_Regular_otf
global _binary_NotoSansCham_Regular_otf_start
global _binary_NotoSansCham_Regular_otf_end
global _binary_NotoSansCham_Regular_otf_size
_binary_NotoSansCham_Regular_otf:
_binary_NotoSansCham_Regular_otf_start:
    db 0
_binary_NotoSansCham_Regular_otf_end:
_binary_NotoSansCham_Regular_otf_size: dq 0

global _binary_NotoSansCherokee_Regular_otf
global _binary_NotoSansCherokee_Regular_otf_start
global _binary_NotoSansCherokee_Regular_otf_end
global _binary_NotoSansCherokee_Regular_otf_size
_binary_NotoSansCherokee_Regular_otf:
_binary_NotoSansCherokee_Regular_otf_start:
    db 0
_binary_NotoSansCherokee_Regular_otf_end:
_binary_NotoSansCherokee_Regular_otf_size: dq 0

global _binary_NotoSansChorasmian_Regular_otf
global _binary_NotoSansChorasmian_Regular_otf_start
global _binary_NotoSansChorasmian_Regular_otf_end
global _binary_NotoSansChorasmian_Regular_otf_size
_binary_NotoSansChorasmian_Regular_otf:
_binary_NotoSansChorasmian_Regular_otf_start:
    db 0
_binary_NotoSansChorasmian_Regular_otf_end:
_binary_NotoSansChorasmian_Regular_otf_size: dq 0

global _binary_NotoSansCoptic_Regular_otf
global _binary_NotoSansCoptic_Regular_otf_start
global _binary_NotoSansCoptic_Regular_otf_end
global _binary_NotoSansCoptic_Regular_otf_size
_binary_NotoSansCoptic_Regular_otf:
_binary_NotoSansCoptic_Regular_otf_start:
    db 0
_binary_NotoSansCoptic_Regular_otf_end:
_binary_NotoSansCoptic_Regular_otf_size: dq 0

global _binary_NotoSansCuneiform_Regular_otf
global _binary_NotoSansCuneiform_Regular_otf_start
global _binary_NotoSansCuneiform_Regular_otf_end
global _binary_NotoSansCuneiform_Regular_otf_size
_binary_NotoSansCuneiform_Regular_otf:
_binary_NotoSansCuneiform_Regular_otf_start:
    db 0
_binary_NotoSansCuneiform_Regular_otf_end:
_binary_NotoSansCuneiform_Regular_otf_size: dq 0

global _binary_NotoSansCypriot_Regular_otf
global _binary_NotoSansCypriot_Regular_otf_start
global _binary_NotoSansCypriot_Regular_otf_end
global _binary_NotoSansCypriot_Regular_otf_size
_binary_NotoSansCypriot_Regular_otf:
_binary_NotoSansCypriot_Regular_otf_start:
    db 0
_binary_NotoSansCypriot_Regular_otf_end:
_binary_NotoSansCypriot_Regular_otf_size: dq 0

global _binary_NotoSansCyproMinoan_Regular_otf
global _binary_NotoSansCyproMinoan_Regular_otf_start
global _binary_NotoSansCyproMinoan_Regular_otf_end
global _binary_NotoSansCyproMinoan_Regular_otf_size
_binary_NotoSansCyproMinoan_Regular_otf:
_binary_NotoSansCyproMinoan_Regular_otf_start:
    db 0
_binary_NotoSansCyproMinoan_Regular_otf_end:
_binary_NotoSansCyproMinoan_Regular_otf_size: dq 0

global _binary_NotoSansDeseret_Regular_otf
global _binary_NotoSansDeseret_Regular_otf_start
global _binary_NotoSansDeseret_Regular_otf_end
global _binary_NotoSansDeseret_Regular_otf_size
_binary_NotoSansDeseret_Regular_otf:
_binary_NotoSansDeseret_Regular_otf_start:
    db 0
_binary_NotoSansDeseret_Regular_otf_end:
_binary_NotoSansDeseret_Regular_otf_size: dq 0

global _binary_NotoSansDivesAkuru_Regular_otf
global _binary_NotoSansDivesAkuru_Regular_otf_start
global _binary_NotoSansDivesAkuru_Regular_otf_end
global _binary_NotoSansDivesAkuru_Regular_otf_size
_binary_NotoSansDivesAkuru_Regular_otf:
_binary_NotoSansDivesAkuru_Regular_otf_start:
    db 0
_binary_NotoSansDivesAkuru_Regular_otf_end:
_binary_NotoSansDivesAkuru_Regular_otf_size: dq 0

global _binary_NotoSansDuployan_Regular_otf
global _binary_NotoSansDuployan_Regular_otf_start
global _binary_NotoSansDuployan_Regular_otf_end
global _binary_NotoSansDuployan_Regular_otf_size
_binary_NotoSansDuployan_Regular_otf:
_binary_NotoSansDuployan_Regular_otf_start:
    db 0
_binary_NotoSansDuployan_Regular_otf_end:
_binary_NotoSansDuployan_Regular_otf_size: dq 0

global _binary_NotoSansEgyptianHieroglyphs_Regular_otf
global _binary_NotoSansEgyptianHieroglyphs_Regular_otf_start
global _binary_NotoSansEgyptianHieroglyphs_Regular_otf_end
global _binary_NotoSansEgyptianHieroglyphs_Regular_otf_size
_binary_NotoSansEgyptianHieroglyphs_Regular_otf:
_binary_NotoSansEgyptianHieroglyphs_Regular_otf_start:
    db 0
_binary_NotoSansEgyptianHieroglyphs_Regular_otf_end:
_binary_NotoSansEgyptianHieroglyphs_Regular_otf_size: dq 0

global _binary_NotoSansElbasan_Regular_otf
global _binary_NotoSansElbasan_Regular_otf_start
global _binary_NotoSansElbasan_Regular_otf_end
global _binary_NotoSansElbasan_Regular_otf_size
_binary_NotoSansElbasan_Regular_otf:
_binary_NotoSansElbasan_Regular_otf_start:
    db 0
_binary_NotoSansElbasan_Regular_otf_end:
_binary_NotoSansElbasan_Regular_otf_size: dq 0

global _binary_NotoSansElymaic_Regular_otf
global _binary_NotoSansElymaic_Regular_otf_start
global _binary_NotoSansElymaic_Regular_otf_end
global _binary_NotoSansElymaic_Regular_otf_size
_binary_NotoSansElymaic_Regular_otf:
_binary_NotoSansElymaic_Regular_otf_start:
    db 0
_binary_NotoSansElymaic_Regular_otf_end:
_binary_NotoSansElymaic_Regular_otf_size: dq 0

global _binary_NotoSansGlagolitic_Regular_otf
global _binary_NotoSansGlagolitic_Regular_otf_start
global _binary_NotoSansGlagolitic_Regular_otf_end
global _binary_NotoSansGlagolitic_Regular_otf_size
_binary_NotoSansGlagolitic_Regular_otf:
_binary_NotoSansGlagolitic_Regular_otf_start:
    db 0
_binary_NotoSansGlagolitic_Regular_otf_end:
_binary_NotoSansGlagolitic_Regular_otf_size: dq 0

global _binary_NotoSansGothic_Regular_otf
global _binary_NotoSansGothic_Regular_otf_start
global _binary_NotoSansGothic_Regular_otf_end
global _binary_NotoSansGothic_Regular_otf_size
_binary_NotoSansGothic_Regular_otf:
_binary_NotoSansGothic_Regular_otf_start:
    db 0
_binary_NotoSansGothic_Regular_otf_end:
_binary_NotoSansGothic_Regular_otf_size: dq 0

global _binary_NotoSansGunjalaGondi_Regular_otf
global _binary_NotoSansGunjalaGondi_Regular_otf_start
global _binary_NotoSansGunjalaGondi_Regular_otf_end
global _binary_NotoSansGunjalaGondi_Regular_otf_size
_binary_NotoSansGunjalaGondi_Regular_otf:
_binary_NotoSansGunjalaGondi_Regular_otf_start:
    db 0
_binary_NotoSansGunjalaGondi_Regular_otf_end:
_binary_NotoSansGunjalaGondi_Regular_otf_size: dq 0

global _binary_NotoSansHanifiRohingya_Regular_otf
global _binary_NotoSansHanifiRohingya_Regular_otf_start
global _binary_NotoSansHanifiRohingya_Regular_otf_end
global _binary_NotoSansHanifiRohingya_Regular_otf_size
_binary_NotoSansHanifiRohingya_Regular_otf:
_binary_NotoSansHanifiRohingya_Regular_otf_start:
    db 0
_binary_NotoSansHanifiRohingya_Regular_otf_end:
_binary_NotoSansHanifiRohingya_Regular_otf_size: dq 0

global _binary_NotoSansHanunoo_Regular_otf
global _binary_NotoSansHanunoo_Regular_otf_start
global _binary_NotoSansHanunoo_Regular_otf_end
global _binary_NotoSansHanunoo_Regular_otf_size
_binary_NotoSansHanunoo_Regular_otf:
_binary_NotoSansHanunoo_Regular_otf_start:
    db 0
_binary_NotoSansHanunoo_Regular_otf_end:
_binary_NotoSansHanunoo_Regular_otf_size: dq 0

global _binary_NotoSansHatran_Regular_otf
global _binary_NotoSansHatran_Regular_otf_start
global _binary_NotoSansHatran_Regular_otf_end
global _binary_NotoSansHatran_Regular_otf_size
_binary_NotoSansHatran_Regular_otf:
_binary_NotoSansHatran_Regular_otf_start:
    db 0
_binary_NotoSansHatran_Regular_otf_end:
_binary_NotoSansHatran_Regular_otf_size: dq 0

global _binary_NotoSansImperialAramaic_Regular_otf
global _binary_NotoSansImperialAramaic_Regular_otf_start
global _binary_NotoSansImperialAramaic_Regular_otf_end
global _binary_NotoSansImperialAramaic_Regular_otf_size
_binary_NotoSansImperialAramaic_Regular_otf:
_binary_NotoSansImperialAramaic_Regular_otf_start:
    db 0
_binary_NotoSansImperialAramaic_Regular_otf_end:
_binary_NotoSansImperialAramaic_Regular_otf_size: dq 0

global _binary_NotoSansInscriptionalPahlavi_Regular_otf
global _binary_NotoSansInscriptionalPahlavi_Regular_otf_start
global _binary_NotoSansInscriptionalPahlavi_Regular_otf_end
global _binary_NotoSansInscriptionalPahlavi_Regular_otf_size
_binary_NotoSansInscriptionalPahlavi_Regular_otf:
_binary_NotoSansInscriptionalPahlavi_Regular_otf_start:
    db 0
_binary_NotoSansInscriptionalPahlavi_Regular_otf_end:
_binary_NotoSansInscriptionalPahlavi_Regular_otf_size: dq 0

global _binary_NotoSansInscriptionalParthian_Regular_otf
global _binary_NotoSansInscriptionalParthian_Regular_otf_start
global _binary_NotoSansInscriptionalParthian_Regular_otf_end
global _binary_NotoSansInscriptionalParthian_Regular_otf_size
_binary_NotoSansInscriptionalParthian_Regular_otf:
_binary_NotoSansInscriptionalParthian_Regular_otf_start:
    db 0
_binary_NotoSansInscriptionalParthian_Regular_otf_end:
_binary_NotoSansInscriptionalParthian_Regular_otf_size: dq 0

global _binary_NotoSansJavanese_Regular_otf
global _binary_NotoSansJavanese_Regular_otf_start
global _binary_NotoSansJavanese_Regular_otf_end
global _binary_NotoSansJavanese_Regular_otf_size
_binary_NotoSansJavanese_Regular_otf:
_binary_NotoSansJavanese_Regular_otf_start:
    db 0
_binary_NotoSansJavanese_Regular_otf_end:
_binary_NotoSansJavanese_Regular_otf_size: dq 0

global _binary_NotoSansKaithi_Regular_otf
global _binary_NotoSansKaithi_Regular_otf_start
global _binary_NotoSansKaithi_Regular_otf_end
global _binary_NotoSansKaithi_Regular_otf_size
_binary_NotoSansKaithi_Regular_otf:
_binary_NotoSansKaithi_Regular_otf_start:
    db 0
_binary_NotoSansKaithi_Regular_otf_end:
_binary_NotoSansKaithi_Regular_otf_size: dq 0

global _binary_NotoSansKayahLi_Regular_otf
global _binary_NotoSansKayahLi_Regular_otf_start
global _binary_NotoSansKayahLi_Regular_otf_end
global _binary_NotoSansKayahLi_Regular_otf_size
_binary_NotoSansKayahLi_Regular_otf:
_binary_NotoSansKayahLi_Regular_otf_start:
    db 0
_binary_NotoSansKayahLi_Regular_otf_end:
_binary_NotoSansKayahLi_Regular_otf_size: dq 0

global _binary_NotoSansKharoshthi_Regular_otf
global _binary_NotoSansKharoshthi_Regular_otf_start
global _binary_NotoSansKharoshthi_Regular_otf_end
global _binary_NotoSansKharoshthi_Regular_otf_size
_binary_NotoSansKharoshthi_Regular_otf:
_binary_NotoSansKharoshthi_Regular_otf_start:
    db 0
_binary_NotoSansKharoshthi_Regular_otf_end:
_binary_NotoSansKharoshthi_Regular_otf_size: dq 0

global _binary_NotoSansKhitanSmallScript_Regular_otf
global _binary_NotoSansKhitanSmallScript_Regular_otf_start
global _binary_NotoSansKhitanSmallScript_Regular_otf_end
global _binary_NotoSansKhitanSmallScript_Regular_otf_size
_binary_NotoSansKhitanSmallScript_Regular_otf:
_binary_NotoSansKhitanSmallScript_Regular_otf_start:
    db 0
_binary_NotoSansKhitanSmallScript_Regular_otf_end:
_binary_NotoSansKhitanSmallScript_Regular_otf_size: dq 0

global _binary_NotoSansKhudawadi_Regular_otf
global _binary_NotoSansKhudawadi_Regular_otf_start
global _binary_NotoSansKhudawadi_Regular_otf_end
global _binary_NotoSansKhudawadi_Regular_otf_size
_binary_NotoSansKhudawadi_Regular_otf:
_binary_NotoSansKhudawadi_Regular_otf_start:
    db 0
_binary_NotoSansKhudawadi_Regular_otf_end:
_binary_NotoSansKhudawadi_Regular_otf_size: dq 0

global _binary_NotoSansLepcha_Regular_otf
global _binary_NotoSansLepcha_Regular_otf_start
global _binary_NotoSansLepcha_Regular_otf_end
global _binary_NotoSansLepcha_Regular_otf_size
_binary_NotoSansLepcha_Regular_otf:
_binary_NotoSansLepcha_Regular_otf_start:
    db 0
_binary_NotoSansLepcha_Regular_otf_end:
_binary_NotoSansLepcha_Regular_otf_size: dq 0

global _binary_NotoSansLimbu_Regular_otf
global _binary_NotoSansLimbu_Regular_otf_start
global _binary_NotoSansLimbu_Regular_otf_end
global _binary_NotoSansLimbu_Regular_otf_size
_binary_NotoSansLimbu_Regular_otf:
_binary_NotoSansLimbu_Regular_otf_start:
    db 0
_binary_NotoSansLimbu_Regular_otf_end:
_binary_NotoSansLimbu_Regular_otf_size: dq 0

global _binary_NotoSansLinearA_Regular_otf
global _binary_NotoSansLinearA_Regular_otf_start
global _binary_NotoSansLinearA_Regular_otf_end
global _binary_NotoSansLinearA_Regular_otf_size
_binary_NotoSansLinearA_Regular_otf:
_binary_NotoSansLinearA_Regular_otf_start:
    db 0
_binary_NotoSansLinearA_Regular_otf_end:
_binary_NotoSansLinearA_Regular_otf_size: dq 0

global _binary_NotoSansLinearB_Regular_otf
global _binary_NotoSansLinearB_Regular_otf_start
global _binary_NotoSansLinearB_Regular_otf_end
global _binary_NotoSansLinearB_Regular_otf_size
_binary_NotoSansLinearB_Regular_otf:
_binary_NotoSansLinearB_Regular_otf_start:
    db 0
_binary_NotoSansLinearB_Regular_otf_end:
_binary_NotoSansLinearB_Regular_otf_size: dq 0

global _binary_NotoSansLisu_Regular_otf
global _binary_NotoSansLisu_Regular_otf_start
global _binary_NotoSansLisu_Regular_otf_end
global _binary_NotoSansLisu_Regular_otf_size
_binary_NotoSansLisu_Regular_otf:
_binary_NotoSansLisu_Regular_otf_start:
    db 0
_binary_NotoSansLisu_Regular_otf_end:
_binary_NotoSansLisu_Regular_otf_size: dq 0

global _binary_NotoSansLycian_Regular_otf
global _binary_NotoSansLycian_Regular_otf_start
global _binary_NotoSansLycian_Regular_otf_end
global _binary_NotoSansLycian_Regular_otf_size
_binary_NotoSansLycian_Regular_otf:
_binary_NotoSansLycian_Regular_otf_start:
    db 0
_binary_NotoSansLycian_Regular_otf_end:
_binary_NotoSansLycian_Regular_otf_size: dq 0

global _binary_NotoSansLydian_Regular_otf
global _binary_NotoSansLydian_Regular_otf_start
global _binary_NotoSansLydian_Regular_otf_end
global _binary_NotoSansLydian_Regular_otf_size
_binary_NotoSansLydian_Regular_otf:
_binary_NotoSansLydian_Regular_otf_start:
    db 0
_binary_NotoSansLydian_Regular_otf_end:
_binary_NotoSansLydian_Regular_otf_size: dq 0

global _binary_NotoSansMahajani_Regular_otf
global _binary_NotoSansMahajani_Regular_otf_start
global _binary_NotoSansMahajani_Regular_otf_end
global _binary_NotoSansMahajani_Regular_otf_size
_binary_NotoSansMahajani_Regular_otf:
_binary_NotoSansMahajani_Regular_otf_start:
    db 0
_binary_NotoSansMahajani_Regular_otf_end:
_binary_NotoSansMahajani_Regular_otf_size: dq 0

global _binary_NotoSansMakasar_Regular_otf
global _binary_NotoSansMakasar_Regular_otf_start
global _binary_NotoSansMakasar_Regular_otf_end
global _binary_NotoSansMakasar_Regular_otf_size
_binary_NotoSansMakasar_Regular_otf:
_binary_NotoSansMakasar_Regular_otf_start:
    db 0
_binary_NotoSansMakasar_Regular_otf_end:
_binary_NotoSansMakasar_Regular_otf_size: dq 0

global _binary_NotoSansMandaic_Regular_otf
global _binary_NotoSansMandaic_Regular_otf_start
global _binary_NotoSansMandaic_Regular_otf_end
global _binary_NotoSansMandaic_Regular_otf_size
_binary_NotoSansMandaic_Regular_otf:
_binary_NotoSansMandaic_Regular_otf_start:
    db 0
_binary_NotoSansMandaic_Regular_otf_end:
_binary_NotoSansMandaic_Regular_otf_size: dq 0

global _binary_NotoSansManichaean_Regular_otf
global _binary_NotoSansManichaean_Regular_otf_start
global _binary_NotoSansManichaean_Regular_otf_end
global _binary_NotoSansManichaean_Regular_otf_size
_binary_NotoSansManichaean_Regular_otf:
_binary_NotoSansManichaean_Regular_otf_start:
    db 0
_binary_NotoSansManichaean_Regular_otf_end:
_binary_NotoSansManichaean_Regular_otf_size: dq 0

global _binary_NotoSansMarchen_Regular_otf
global _binary_NotoSansMarchen_Regular_otf_start
global _binary_NotoSansMarchen_Regular_otf_end
global _binary_NotoSansMarchen_Regular_otf_size
_binary_NotoSansMarchen_Regular_otf:
_binary_NotoSansMarchen_Regular_otf_start:
    db 0
_binary_NotoSansMarchen_Regular_otf_end:
_binary_NotoSansMarchen_Regular_otf_size: dq 0

global _binary_NotoSansMasaramGondi_Regular_otf
global _binary_NotoSansMasaramGondi_Regular_otf_start
global _binary_NotoSansMasaramGondi_Regular_otf_end
global _binary_NotoSansMasaramGondi_Regular_otf_size
_binary_NotoSansMasaramGondi_Regular_otf:
_binary_NotoSansMasaramGondi_Regular_otf_start:
    db 0
_binary_NotoSansMasaramGondi_Regular_otf_end:
_binary_NotoSansMasaramGondi_Regular_otf_size: dq 0

global _binary_NotoSansMath_Regular_otf
global _binary_NotoSansMath_Regular_otf_start
global _binary_NotoSansMath_Regular_otf_end
global _binary_NotoSansMath_Regular_otf_size
_binary_NotoSansMath_Regular_otf:
_binary_NotoSansMath_Regular_otf_start:
    db 0
_binary_NotoSansMath_Regular_otf_end:
_binary_NotoSansMath_Regular_otf_size: dq 0

global _binary_NotoSansMedefaidrin_Regular_otf
global _binary_NotoSansMedefaidrin_Regular_otf_start
global _binary_NotoSansMedefaidrin_Regular_otf_end
global _binary_NotoSansMedefaidrin_Regular_otf_size
_binary_NotoSansMedefaidrin_Regular_otf:
_binary_NotoSansMedefaidrin_Regular_otf_start:
    db 0
_binary_NotoSansMedefaidrin_Regular_otf_end:
_binary_NotoSansMedefaidrin_Regular_otf_size: dq 0

global _binary_NotoSansMeeteiMayek_Regular_otf
global _binary_NotoSansMeeteiMayek_Regular_otf_start
global _binary_NotoSansMeeteiMayek_Regular_otf_end
global _binary_NotoSansMeeteiMayek_Regular_otf_size
_binary_NotoSansMeeteiMayek_Regular_otf:
_binary_NotoSansMeeteiMayek_Regular_otf_start:
    db 0
_binary_NotoSansMeeteiMayek_Regular_otf_end:
_binary_NotoSansMeeteiMayek_Regular_otf_size: dq 0

global _binary_NotoSansMendeKikakui_Regular_otf
global _binary_NotoSansMendeKikakui_Regular_otf_start
global _binary_NotoSansMendeKikakui_Regular_otf_end
global _binary_NotoSansMendeKikakui_Regular_otf_size
_binary_NotoSansMendeKikakui_Regular_otf:
_binary_NotoSansMendeKikakui_Regular_otf_start:
    db 0
_binary_NotoSansMendeKikakui_Regular_otf_end:
_binary_NotoSansMendeKikakui_Regular_otf_size: dq 0

global _binary_NotoSansMeroitic_Regular_otf
global _binary_NotoSansMeroitic_Regular_otf_start
global _binary_NotoSansMeroitic_Regular_otf_end
global _binary_NotoSansMeroitic_Regular_otf_size
_binary_NotoSansMeroitic_Regular_otf:
_binary_NotoSansMeroitic_Regular_otf_start:
    db 0
_binary_NotoSansMeroitic_Regular_otf_end:
_binary_NotoSansMeroitic_Regular_otf_size: dq 0

global _binary_NotoSansMiao_Regular_otf
global _binary_NotoSansMiao_Regular_otf_start
global _binary_NotoSansMiao_Regular_otf_end
global _binary_NotoSansMiao_Regular_otf_size
_binary_NotoSansMiao_Regular_otf:
_binary_NotoSansMiao_Regular_otf_start:
    db 0
_binary_NotoSansMiao_Regular_otf_end:
_binary_NotoSansMiao_Regular_otf_size: dq 0

global _binary_NotoSansModi_Regular_otf
global _binary_NotoSansModi_Regular_otf_start
global _binary_NotoSansModi_Regular_otf_end
global _binary_NotoSansModi_Regular_otf_size
_binary_NotoSansModi_Regular_otf:
_binary_NotoSansModi_Regular_otf_start:
    db 0
_binary_NotoSansModi_Regular_otf_end:
_binary_NotoSansModi_Regular_otf_size: dq 0

global _binary_NotoSansMongolian_Regular_otf
global _binary_NotoSansMongolian_Regular_otf_start
global _binary_NotoSansMongolian_Regular_otf_end
global _binary_NotoSansMongolian_Regular_otf_size
_binary_NotoSansMongolian_Regular_otf:
_binary_NotoSansMongolian_Regular_otf_start:
    db 0
_binary_NotoSansMongolian_Regular_otf_end:
_binary_NotoSansMongolian_Regular_otf_size: dq 0

global _binary_NotoSansMro_Regular_otf
global _binary_NotoSansMro_Regular_otf_start
global _binary_NotoSansMro_Regular_otf_end
global _binary_NotoSansMro_Regular_otf_size
_binary_NotoSansMro_Regular_otf:
_binary_NotoSansMro_Regular_otf_start:
    db 0
_binary_NotoSansMro_Regular_otf_end:
_binary_NotoSansMro_Regular_otf_size: dq 0

global _binary_NotoSansMultani_Regular_otf
global _binary_NotoSansMultani_Regular_otf_start
global _binary_NotoSansMultani_Regular_otf_end
global _binary_NotoSansMultani_Regular_otf_size
_binary_NotoSansMultani_Regular_otf:
_binary_NotoSansMultani_Regular_otf_start:
    db 0
_binary_NotoSansMultani_Regular_otf_end:
_binary_NotoSansMultani_Regular_otf_size: dq 0

global _binary_NotoSansNKo_Regular_otf
global _binary_NotoSansNKo_Regular_otf_start
global _binary_NotoSansNKo_Regular_otf_end
global _binary_NotoSansNKo_Regular_otf_size
_binary_NotoSansNKo_Regular_otf:
_binary_NotoSansNKo_Regular_otf_start:
    db 0
_binary_NotoSansNKo_Regular_otf_end:
_binary_NotoSansNKo_Regular_otf_size: dq 0

global _binary_NotoSansNabataean_Regular_otf
global _binary_NotoSansNabataean_Regular_otf_start
global _binary_NotoSansNabataean_Regular_otf_end
global _binary_NotoSansNabataean_Regular_otf_size
_binary_NotoSansNabataean_Regular_otf:
_binary_NotoSansNabataean_Regular_otf_start:
    db 0
_binary_NotoSansNabataean_Regular_otf_end:
_binary_NotoSansNabataean_Regular_otf_size: dq 0

global _binary_NotoSansNandinagari_Regular_otf
global _binary_NotoSansNandinagari_Regular_otf_start
global _binary_NotoSansNandinagari_Regular_otf_end
global _binary_NotoSansNandinagari_Regular_otf_size
_binary_NotoSansNandinagari_Regular_otf:
_binary_NotoSansNandinagari_Regular_otf_start:
    db 0
_binary_NotoSansNandinagari_Regular_otf_end:
_binary_NotoSansNandinagari_Regular_otf_size: dq 0

global _binary_NotoSansNewTaiLue_Regular_otf
global _binary_NotoSansNewTaiLue_Regular_otf_start
global _binary_NotoSansNewTaiLue_Regular_otf_end
global _binary_NotoSansNewTaiLue_Regular_otf_size
_binary_NotoSansNewTaiLue_Regular_otf:
_binary_NotoSansNewTaiLue_Regular_otf_start:
    db 0
_binary_NotoSansNewTaiLue_Regular_otf_end:
_binary_NotoSansNewTaiLue_Regular_otf_size: dq 0

global _binary_NotoSansNewa_Regular_otf
global _binary_NotoSansNewa_Regular_otf_start
global _binary_NotoSansNewa_Regular_otf_end
global _binary_NotoSansNewa_Regular_otf_size
_binary_NotoSansNewa_Regular_otf:
_binary_NotoSansNewa_Regular_otf_start:
    db 0
_binary_NotoSansNewa_Regular_otf_end:
_binary_NotoSansNewa_Regular_otf_size: dq 0

global _binary_NotoSansNushu_Regular_otf
global _binary_NotoSansNushu_Regular_otf_start
global _binary_NotoSansNushu_Regular_otf_end
global _binary_NotoSansNushu_Regular_otf_size
_binary_NotoSansNushu_Regular_otf:
_binary_NotoSansNushu_Regular_otf_start:
    db 0
_binary_NotoSansNushu_Regular_otf_end:
_binary_NotoSansNushu_Regular_otf_size: dq 0

global _binary_NotoSansOgham_Regular_otf
global _binary_NotoSansOgham_Regular_otf_start
global _binary_NotoSansOgham_Regular_otf_end
global _binary_NotoSansOgham_Regular_otf_size
_binary_NotoSansOgham_Regular_otf:
_binary_NotoSansOgham_Regular_otf_start:
    db 0
_binary_NotoSansOgham_Regular_otf_end:
_binary_NotoSansOgham_Regular_otf_size: dq 0

global _binary_NotoSansOlChiki_Regular_otf
global _binary_NotoSansOlChiki_Regular_otf_start
global _binary_NotoSansOlChiki_Regular_otf_end
global _binary_NotoSansOlChiki_Regular_otf_size
_binary_NotoSansOlChiki_Regular_otf:
_binary_NotoSansOlChiki_Regular_otf_start:
    db 0
_binary_NotoSansOlChiki_Regular_otf_end:
_binary_NotoSansOlChiki_Regular_otf_size: dq 0

global _binary_NotoSansOldHungarian_Regular_otf
global _binary_NotoSansOldHungarian_Regular_otf_start
global _binary_NotoSansOldHungarian_Regular_otf_end
global _binary_NotoSansOldHungarian_Regular_otf_size
_binary_NotoSansOldHungarian_Regular_otf:
_binary_NotoSansOldHungarian_Regular_otf_start:
    db 0
_binary_NotoSansOldHungarian_Regular_otf_end:
_binary_NotoSansOldHungarian_Regular_otf_size: dq 0

global _binary_NotoSansOldItalic_Regular_otf
global _binary_NotoSansOldItalic_Regular_otf_start
global _binary_NotoSansOldItalic_Regular_otf_end
global _binary_NotoSansOldItalic_Regular_otf_size
_binary_NotoSansOldItalic_Regular_otf:
_binary_NotoSansOldItalic_Regular_otf_start:
    db 0
_binary_NotoSansOldItalic_Regular_otf_end:
_binary_NotoSansOldItalic_Regular_otf_size: dq 0

global _binary_NotoSansOldNorthArabian_Regular_otf
global _binary_NotoSansOldNorthArabian_Regular_otf_start
global _binary_NotoSansOldNorthArabian_Regular_otf_end
global _binary_NotoSansOldNorthArabian_Regular_otf_size
_binary_NotoSansOldNorthArabian_Regular_otf:
_binary_NotoSansOldNorthArabian_Regular_otf_start:
    db 0
_binary_NotoSansOldNorthArabian_Regular_otf_end:
_binary_NotoSansOldNorthArabian_Regular_otf_size: dq 0

global _binary_NotoSansOldPermic_Regular_otf
global _binary_NotoSansOldPermic_Regular_otf_start
global _binary_NotoSansOldPermic_Regular_otf_end
global _binary_NotoSansOldPermic_Regular_otf_size
_binary_NotoSansOldPermic_Regular_otf:
_binary_NotoSansOldPermic_Regular_otf_start:
    db 0
_binary_NotoSansOldPermic_Regular_otf_end:
_binary_NotoSansOldPermic_Regular_otf_size: dq 0

global _binary_NotoSansOldPersian_Regular_otf
global _binary_NotoSansOldPersian_Regular_otf_start
global _binary_NotoSansOldPersian_Regular_otf_end
global _binary_NotoSansOldPersian_Regular_otf_size
_binary_NotoSansOldPersian_Regular_otf:
_binary_NotoSansOldPersian_Regular_otf_start:
    db 0
_binary_NotoSansOldPersian_Regular_otf_end:
_binary_NotoSansOldPersian_Regular_otf_size: dq 0

global _binary_NotoSansOldSogdian_Regular_otf
global _binary_NotoSansOldSogdian_Regular_otf_start
global _binary_NotoSansOldSogdian_Regular_otf_end
global _binary_NotoSansOldSogdian_Regular_otf_size
_binary_NotoSansOldSogdian_Regular_otf:
_binary_NotoSansOldSogdian_Regular_otf_start:
    db 0
_binary_NotoSansOldSogdian_Regular_otf_end:
_binary_NotoSansOldSogdian_Regular_otf_size: dq 0

global _binary_NotoSansOldSouthArabian_Regular_otf
global _binary_NotoSansOldSouthArabian_Regular_otf_start
global _binary_NotoSansOldSouthArabian_Regular_otf_end
global _binary_NotoSansOldSouthArabian_Regular_otf_size
_binary_NotoSansOldSouthArabian_Regular_otf:
_binary_NotoSansOldSouthArabian_Regular_otf_start:
    db 0
_binary_NotoSansOldSouthArabian_Regular_otf_end:
_binary_NotoSansOldSouthArabian_Regular_otf_size: dq 0

global _binary_NotoSansOldTurkic_Regular_otf
global _binary_NotoSansOldTurkic_Regular_otf_start
global _binary_NotoSansOldTurkic_Regular_otf_end
global _binary_NotoSansOldTurkic_Regular_otf_size
_binary_NotoSansOldTurkic_Regular_otf:
_binary_NotoSansOldTurkic_Regular_otf_start:
    db 0
_binary_NotoSansOldTurkic_Regular_otf_end:
_binary_NotoSansOldTurkic_Regular_otf_size: dq 0

global _binary_NotoSansOldUyghur_Regular_otf
global _binary_NotoSansOldUyghur_Regular_otf_start
global _binary_NotoSansOldUyghur_Regular_otf_end
global _binary_NotoSansOldUyghur_Regular_otf_size
_binary_NotoSansOldUyghur_Regular_otf:
_binary_NotoSansOldUyghur_Regular_otf_start:
    db 0
_binary_NotoSansOldUyghur_Regular_otf_end:
_binary_NotoSansOldUyghur_Regular_otf_size: dq 0

global _binary_NotoSansOriya_Regular_otf
global _binary_NotoSansOriya_Regular_otf_start
global _binary_NotoSansOriya_Regular_otf_end
global _binary_NotoSansOriya_Regular_otf_size
_binary_NotoSansOriya_Regular_otf:
_binary_NotoSansOriya_Regular_otf_start:
    db 0
_binary_NotoSansOriya_Regular_otf_end:
_binary_NotoSansOriya_Regular_otf_size: dq 0

global _binary_NotoSansOsage_Regular_otf
global _binary_NotoSansOsage_Regular_otf_start
global _binary_NotoSansOsage_Regular_otf_end
global _binary_NotoSansOsage_Regular_otf_size
_binary_NotoSansOsage_Regular_otf:
_binary_NotoSansOsage_Regular_otf_start:
    db 0
_binary_NotoSansOsage_Regular_otf_end:
_binary_NotoSansOsage_Regular_otf_size: dq 0

global _binary_NotoSansOsmanya_Regular_otf
global _binary_NotoSansOsmanya_Regular_otf_start
global _binary_NotoSansOsmanya_Regular_otf_end
global _binary_NotoSansOsmanya_Regular_otf_size
_binary_NotoSansOsmanya_Regular_otf:
_binary_NotoSansOsmanya_Regular_otf_start:
    db 0
_binary_NotoSansOsmanya_Regular_otf_end:
_binary_NotoSansOsmanya_Regular_otf_size: dq 0

global _binary_NotoSansPahawhHmong_Regular_otf
global _binary_NotoSansPahawhHmong_Regular_otf_start
global _binary_NotoSansPahawhHmong_Regular_otf_end
global _binary_NotoSansPahawhHmong_Regular_otf_size
_binary_NotoSansPahawhHmong_Regular_otf:
_binary_NotoSansPahawhHmong_Regular_otf_start:
    db 0
_binary_NotoSansPahawhHmong_Regular_otf_end:
_binary_NotoSansPahawhHmong_Regular_otf_size: dq 0

global _binary_NotoSansPalmyrene_Regular_otf
global _binary_NotoSansPalmyrene_Regular_otf_start
global _binary_NotoSansPalmyrene_Regular_otf_end
global _binary_NotoSansPalmyrene_Regular_otf_size
_binary_NotoSansPalmyrene_Regular_otf:
_binary_NotoSansPalmyrene_Regular_otf_start:
    db 0
_binary_NotoSansPalmyrene_Regular_otf_end:
_binary_NotoSansPalmyrene_Regular_otf_size: dq 0

global _binary_NotoSansPauCinHau_Regular_otf
global _binary_NotoSansPauCinHau_Regular_otf_start
global _binary_NotoSansPauCinHau_Regular_otf_end
global _binary_NotoSansPauCinHau_Regular_otf_size
_binary_NotoSansPauCinHau_Regular_otf:
_binary_NotoSansPauCinHau_Regular_otf_start:
    db 0
_binary_NotoSansPauCinHau_Regular_otf_end:
_binary_NotoSansPauCinHau_Regular_otf_size: dq 0

global _binary_NotoSansPhagsPa_Regular_otf
global _binary_NotoSansPhagsPa_Regular_otf_start
global _binary_NotoSansPhagsPa_Regular_otf_end
global _binary_NotoSansPhagsPa_Regular_otf_size
_binary_NotoSansPhagsPa_Regular_otf:
_binary_NotoSansPhagsPa_Regular_otf_start:
    db 0
_binary_NotoSansPhagsPa_Regular_otf_end:
_binary_NotoSansPhagsPa_Regular_otf_size: dq 0

global _binary_NotoSansPhoenician_Regular_otf
global _binary_NotoSansPhoenician_Regular_otf_start
global _binary_NotoSansPhoenician_Regular_otf_end
global _binary_NotoSansPhoenician_Regular_otf_size
_binary_NotoSansPhoenician_Regular_otf:
_binary_NotoSansPhoenician_Regular_otf_start:
    db 0
_binary_NotoSansPhoenician_Regular_otf_end:
_binary_NotoSansPhoenician_Regular_otf_size: dq 0

global _binary_NotoSansPsalterPahlavi_Regular_otf
global _binary_NotoSansPsalterPahlavi_Regular_otf_start
global _binary_NotoSansPsalterPahlavi_Regular_otf_end
global _binary_NotoSansPsalterPahlavi_Regular_otf_size
_binary_NotoSansPsalterPahlavi_Regular_otf:
_binary_NotoSansPsalterPahlavi_Regular_otf_start:
    db 0
_binary_NotoSansPsalterPahlavi_Regular_otf_end:
_binary_NotoSansPsalterPahlavi_Regular_otf_size: dq 0

global _binary_NotoSansRejang_Regular_otf
global _binary_NotoSansRejang_Regular_otf_start
global _binary_NotoSansRejang_Regular_otf_end
global _binary_NotoSansRejang_Regular_otf_size
_binary_NotoSansRejang_Regular_otf:
_binary_NotoSansRejang_Regular_otf_start:
    db 0
_binary_NotoSansRejang_Regular_otf_end:
_binary_NotoSansRejang_Regular_otf_size: dq 0

global _binary_NotoSansRunic_Regular_otf
global _binary_NotoSansRunic_Regular_otf_start
global _binary_NotoSansRunic_Regular_otf_end
global _binary_NotoSansRunic_Regular_otf_size
_binary_NotoSansRunic_Regular_otf:
_binary_NotoSansRunic_Regular_otf_start:
    db 0
_binary_NotoSansRunic_Regular_otf_end:
_binary_NotoSansRunic_Regular_otf_size: dq 0

global _binary_NotoSansSamaritan_Regular_otf
global _binary_NotoSansSamaritan_Regular_otf_start
global _binary_NotoSansSamaritan_Regular_otf_end
global _binary_NotoSansSamaritan_Regular_otf_size
_binary_NotoSansSamaritan_Regular_otf:
_binary_NotoSansSamaritan_Regular_otf_start:
    db 0
_binary_NotoSansSamaritan_Regular_otf_end:
_binary_NotoSansSamaritan_Regular_otf_size: dq 0

global _binary_NotoSansSaurashtra_Regular_otf
global _binary_NotoSansSaurashtra_Regular_otf_start
global _binary_NotoSansSaurashtra_Regular_otf_end
global _binary_NotoSansSaurashtra_Regular_otf_size
_binary_NotoSansSaurashtra_Regular_otf:
_binary_NotoSansSaurashtra_Regular_otf_start:
    db 0
_binary_NotoSansSaurashtra_Regular_otf_end:
_binary_NotoSansSaurashtra_Regular_otf_size: dq 0

global _binary_NotoSansSharada_Regular_otf
global _binary_NotoSansSharada_Regular_otf_start
global _binary_NotoSansSharada_Regular_otf_end
global _binary_NotoSansSharada_Regular_otf_size
_binary_NotoSansSharada_Regular_otf:
_binary_NotoSansSharada_Regular_otf_start:
    db 0
_binary_NotoSansSharada_Regular_otf_end:
_binary_NotoSansSharada_Regular_otf_size: dq 0

global _binary_NotoSansShavian_Regular_otf
global _binary_NotoSansShavian_Regular_otf_start
global _binary_NotoSansShavian_Regular_otf_end
global _binary_NotoSansShavian_Regular_otf_size
_binary_NotoSansShavian_Regular_otf:
_binary_NotoSansShavian_Regular_otf_start:
    db 0
_binary_NotoSansShavian_Regular_otf_end:
_binary_NotoSansShavian_Regular_otf_size: dq 0

global _binary_NotoSansSiddham_Regular_otf
global _binary_NotoSansSiddham_Regular_otf_start
global _binary_NotoSansSiddham_Regular_otf_end
global _binary_NotoSansSiddham_Regular_otf_size
_binary_NotoSansSiddham_Regular_otf:
_binary_NotoSansSiddham_Regular_otf_start:
    db 0
_binary_NotoSansSiddham_Regular_otf_end:
_binary_NotoSansSiddham_Regular_otf_size: dq 0

global _binary_NotoSansSignwriting_Regular_otf
global _binary_NotoSansSignwriting_Regular_otf_start
global _binary_NotoSansSignwriting_Regular_otf_end
global _binary_NotoSansSignwriting_Regular_otf_size
_binary_NotoSansSignwriting_Regular_otf:
_binary_NotoSansSignwriting_Regular_otf_start:
    db 0
_binary_NotoSansSignwriting_Regular_otf_end:
_binary_NotoSansSignwriting_Regular_otf_size: dq 0

global _binary_NotoSansSogdian_Regular_otf
global _binary_NotoSansSogdian_Regular_otf_start
global _binary_NotoSansSogdian_Regular_otf_end
global _binary_NotoSansSogdian_Regular_otf_size
_binary_NotoSansSogdian_Regular_otf:
_binary_NotoSansSogdian_Regular_otf_start:
    db 0
_binary_NotoSansSogdian_Regular_otf_end:
_binary_NotoSansSogdian_Regular_otf_size: dq 0

global _binary_NotoSansSoraSompeng_Regular_otf
global _binary_NotoSansSoraSompeng_Regular_otf_start
global _binary_NotoSansSoraSompeng_Regular_otf_end
global _binary_NotoSansSoraSompeng_Regular_otf_size
_binary_NotoSansSoraSompeng_Regular_otf:
_binary_NotoSansSoraSompeng_Regular_otf_start:
    db 0
_binary_NotoSansSoraSompeng_Regular_otf_end:
_binary_NotoSansSoraSompeng_Regular_otf_size: dq 0

global _binary_NotoSansSoyombo_Regular_otf
global _binary_NotoSansSoyombo_Regular_otf_start
global _binary_NotoSansSoyombo_Regular_otf_end
global _binary_NotoSansSoyombo_Regular_otf_size
_binary_NotoSansSoyombo_Regular_otf:
_binary_NotoSansSoyombo_Regular_otf_start:
    db 0
_binary_NotoSansSoyombo_Regular_otf_end:
_binary_NotoSansSoyombo_Regular_otf_size: dq 0

global _binary_NotoSansSundanese_Regular_otf
global _binary_NotoSansSundanese_Regular_otf_start
global _binary_NotoSansSundanese_Regular_otf_end
global _binary_NotoSansSundanese_Regular_otf_size
_binary_NotoSansSundanese_Regular_otf:
_binary_NotoSansSundanese_Regular_otf_start:
    db 0
_binary_NotoSansSundanese_Regular_otf_end:
_binary_NotoSansSundanese_Regular_otf_size: dq 0

global _binary_NotoSansSylotiNagri_Regular_otf
global _binary_NotoSansSylotiNagri_Regular_otf_start
global _binary_NotoSansSylotiNagri_Regular_otf_end
global _binary_NotoSansSylotiNagri_Regular_otf_size
_binary_NotoSansSylotiNagri_Regular_otf:
_binary_NotoSansSylotiNagri_Regular_otf_start:
    db 0
_binary_NotoSansSylotiNagri_Regular_otf_end:
_binary_NotoSansSylotiNagri_Regular_otf_size: dq 0

global _binary_NotoSansSymbols2_Regular_otf
global _binary_NotoSansSymbols2_Regular_otf_start
global _binary_NotoSansSymbols2_Regular_otf_end
global _binary_NotoSansSymbols2_Regular_otf_size
_binary_NotoSansSymbols2_Regular_otf:
_binary_NotoSansSymbols2_Regular_otf_start:
    db 0
_binary_NotoSansSymbols2_Regular_otf_end:
_binary_NotoSansSymbols2_Regular_otf_size: dq 0

global _binary_NotoSansSymbols_Regular_otf
global _binary_NotoSansSymbols_Regular_otf_start
global _binary_NotoSansSymbols_Regular_otf_end
global _binary_NotoSansSymbols_Regular_otf_size
_binary_NotoSansSymbols_Regular_otf:
_binary_NotoSansSymbols_Regular_otf_start:
    db 0
_binary_NotoSansSymbols_Regular_otf_end:
_binary_NotoSansSymbols_Regular_otf_size: dq 0

global _binary_NotoSansSyriac_Regular_otf
global _binary_NotoSansSyriac_Regular_otf_start
global _binary_NotoSansSyriac_Regular_otf_end
global _binary_NotoSansSyriac_Regular_otf_size
_binary_NotoSansSyriac_Regular_otf:
_binary_NotoSansSyriac_Regular_otf_start:
    db 0
_binary_NotoSansSyriac_Regular_otf_end:
_binary_NotoSansSyriac_Regular_otf_size: dq 0

global _binary_NotoSansTagalog_Regular_otf
global _binary_NotoSansTagalog_Regular_otf_start
global _binary_NotoSansTagalog_Regular_otf_end
global _binary_NotoSansTagalog_Regular_otf_size
_binary_NotoSansTagalog_Regular_otf:
_binary_NotoSansTagalog_Regular_otf_start:
    db 0
_binary_NotoSansTagalog_Regular_otf_end:
_binary_NotoSansTagalog_Regular_otf_size: dq 0

global _binary_NotoSansTagbanwa_Regular_otf
global _binary_NotoSansTagbanwa_Regular_otf_start
global _binary_NotoSansTagbanwa_Regular_otf_end
global _binary_NotoSansTagbanwa_Regular_otf_size
_binary_NotoSansTagbanwa_Regular_otf:
_binary_NotoSansTagbanwa_Regular_otf_start:
    db 0
_binary_NotoSansTagbanwa_Regular_otf_end:
_binary_NotoSansTagbanwa_Regular_otf_size: dq 0

global _binary_NotoSansTaiLe_Regular_otf
global _binary_NotoSansTaiLe_Regular_otf_start
global _binary_NotoSansTaiLe_Regular_otf_end
global _binary_NotoSansTaiLe_Regular_otf_size
_binary_NotoSansTaiLe_Regular_otf:
_binary_NotoSansTaiLe_Regular_otf_start:
    db 0
_binary_NotoSansTaiLe_Regular_otf_end:
_binary_NotoSansTaiLe_Regular_otf_size: dq 0

global _binary_NotoSansTaiTham_Regular_otf
global _binary_NotoSansTaiTham_Regular_otf_start
global _binary_NotoSansTaiTham_Regular_otf_end
global _binary_NotoSansTaiTham_Regular_otf_size
_binary_NotoSansTaiTham_Regular_otf:
_binary_NotoSansTaiTham_Regular_otf_start:
    db 0
_binary_NotoSansTaiTham_Regular_otf_end:
_binary_NotoSansTaiTham_Regular_otf_size: dq 0

global _binary_NotoSansTaiViet_Regular_otf
global _binary_NotoSansTaiViet_Regular_otf_start
global _binary_NotoSansTaiViet_Regular_otf_end
global _binary_NotoSansTaiViet_Regular_otf_size
_binary_NotoSansTaiViet_Regular_otf:
_binary_NotoSansTaiViet_Regular_otf_start:
    db 0
_binary_NotoSansTaiViet_Regular_otf_end:
_binary_NotoSansTaiViet_Regular_otf_size: dq 0

global _binary_NotoSansTakri_Regular_otf
global _binary_NotoSansTakri_Regular_otf_start
global _binary_NotoSansTakri_Regular_otf_end
global _binary_NotoSansTakri_Regular_otf_size
_binary_NotoSansTakri_Regular_otf:
_binary_NotoSansTakri_Regular_otf_start:
    db 0
_binary_NotoSansTakri_Regular_otf_end:
_binary_NotoSansTakri_Regular_otf_size: dq 0

global _binary_NotoSansTangsa_Regular_otf
global _binary_NotoSansTangsa_Regular_otf_start
global _binary_NotoSansTangsa_Regular_otf_end
global _binary_NotoSansTangsa_Regular_otf_size
_binary_NotoSansTangsa_Regular_otf:
_binary_NotoSansTangsa_Regular_otf_start:
    db 0
_binary_NotoSansTangsa_Regular_otf_end:
_binary_NotoSansTangsa_Regular_otf_size: dq 0

global _binary_NotoSansThaana_Regular_otf
global _binary_NotoSansThaana_Regular_otf_start
global _binary_NotoSansThaana_Regular_otf_end
global _binary_NotoSansThaana_Regular_otf_size
_binary_NotoSansThaana_Regular_otf:
_binary_NotoSansThaana_Regular_otf_start:
    db 0
_binary_NotoSansThaana_Regular_otf_end:
_binary_NotoSansThaana_Regular_otf_size: dq 0

global _binary_NotoSansTifinagh_Regular_otf
global _binary_NotoSansTifinagh_Regular_otf_start
global _binary_NotoSansTifinagh_Regular_otf_end
global _binary_NotoSansTifinagh_Regular_otf_size
_binary_NotoSansTifinagh_Regular_otf:
_binary_NotoSansTifinagh_Regular_otf_start:
    db 0
_binary_NotoSansTifinagh_Regular_otf_end:
_binary_NotoSansTifinagh_Regular_otf_size: dq 0

global _binary_NotoSansTirhuta_Regular_otf
global _binary_NotoSansTirhuta_Regular_otf_start
global _binary_NotoSansTirhuta_Regular_otf_end
global _binary_NotoSansTirhuta_Regular_otf_size
_binary_NotoSansTirhuta_Regular_otf:
_binary_NotoSansTirhuta_Regular_otf_start:
    db 0
_binary_NotoSansTirhuta_Regular_otf_end:
_binary_NotoSansTirhuta_Regular_otf_size: dq 0

global _binary_NotoSansToto_Regular_otf
global _binary_NotoSansToto_Regular_otf_start
global _binary_NotoSansToto_Regular_otf_end
global _binary_NotoSansToto_Regular_otf_size
_binary_NotoSansToto_Regular_otf:
_binary_NotoSansToto_Regular_otf_start:
    db 0
_binary_NotoSansToto_Regular_otf_end:
_binary_NotoSansToto_Regular_otf_size: dq 0

global _binary_NotoSansUgaritic_Regular_otf
global _binary_NotoSansUgaritic_Regular_otf_start
global _binary_NotoSansUgaritic_Regular_otf_end
global _binary_NotoSansUgaritic_Regular_otf_size
_binary_NotoSansUgaritic_Regular_otf:
_binary_NotoSansUgaritic_Regular_otf_start:
    db 0
_binary_NotoSansUgaritic_Regular_otf_end:
_binary_NotoSansUgaritic_Regular_otf_size: dq 0

global _binary_NotoSansVai_Regular_otf
global _binary_NotoSansVai_Regular_otf_start
global _binary_NotoSansVai_Regular_otf_end
global _binary_NotoSansVai_Regular_otf_size
_binary_NotoSansVai_Regular_otf:
_binary_NotoSansVai_Regular_otf_start:
    db 0
_binary_NotoSansVai_Regular_otf_end:
_binary_NotoSansVai_Regular_otf_size: dq 0

global _binary_NotoSansVithkuqi_Regular_otf
global _binary_NotoSansVithkuqi_Regular_otf_start
global _binary_NotoSansVithkuqi_Regular_otf_end
global _binary_NotoSansVithkuqi_Regular_otf_size
_binary_NotoSansVithkuqi_Regular_otf:
_binary_NotoSansVithkuqi_Regular_otf_start:
    db 0
_binary_NotoSansVithkuqi_Regular_otf_end:
_binary_NotoSansVithkuqi_Regular_otf_size: dq 0

global _binary_NotoSansWancho_Regular_otf
global _binary_NotoSansWancho_Regular_otf_start
global _binary_NotoSansWancho_Regular_otf_end
global _binary_NotoSansWancho_Regular_otf_size
_binary_NotoSansWancho_Regular_otf:
_binary_NotoSansWancho_Regular_otf_start:
    db 0
_binary_NotoSansWancho_Regular_otf_end:
_binary_NotoSansWancho_Regular_otf_size: dq 0

global _binary_NotoSansWarangCiti_Regular_otf
global _binary_NotoSansWarangCiti_Regular_otf_start
global _binary_NotoSansWarangCiti_Regular_otf_end
global _binary_NotoSansWarangCiti_Regular_otf_size
_binary_NotoSansWarangCiti_Regular_otf:
_binary_NotoSansWarangCiti_Regular_otf_start:
    db 0
_binary_NotoSansWarangCiti_Regular_otf_end:
_binary_NotoSansWarangCiti_Regular_otf_size: dq 0

global _binary_NotoSansYi_Regular_otf
global _binary_NotoSansYi_Regular_otf_start
global _binary_NotoSansYi_Regular_otf_end
global _binary_NotoSansYi_Regular_otf_size
_binary_NotoSansYi_Regular_otf:
_binary_NotoSansYi_Regular_otf_start:
    db 0
_binary_NotoSansYi_Regular_otf_end:
_binary_NotoSansYi_Regular_otf_size: dq 0

global _binary_NotoSansZanabazarSquare_Regular_otf
global _binary_NotoSansZanabazarSquare_Regular_otf_start
global _binary_NotoSansZanabazarSquare_Regular_otf_end
global _binary_NotoSansZanabazarSquare_Regular_otf_size
_binary_NotoSansZanabazarSquare_Regular_otf:
_binary_NotoSansZanabazarSquare_Regular_otf_start:
    db 0
_binary_NotoSansZanabazarSquare_Regular_otf_end:
_binary_NotoSansZanabazarSquare_Regular_otf_size: dq 0

global _binary_NotoSerifAhom_Regular_otf
global _binary_NotoSerifAhom_Regular_otf_start
global _binary_NotoSerifAhom_Regular_otf_end
global _binary_NotoSerifAhom_Regular_otf_size
_binary_NotoSerifAhom_Regular_otf:
_binary_NotoSerifAhom_Regular_otf_start:
    db 0
_binary_NotoSerifAhom_Regular_otf_end:
_binary_NotoSerifAhom_Regular_otf_size: dq 0

global _binary_NotoSerifArmenian_Regular_otf
global _binary_NotoSerifArmenian_Regular_otf_start
global _binary_NotoSerifArmenian_Regular_otf_end
global _binary_NotoSerifArmenian_Regular_otf_size
_binary_NotoSerifArmenian_Regular_otf:
_binary_NotoSerifArmenian_Regular_otf_start:
    db 0
_binary_NotoSerifArmenian_Regular_otf_end:
_binary_NotoSerifArmenian_Regular_otf_size: dq 0

global _binary_NotoSerifBalinese_Regular_otf
global _binary_NotoSerifBalinese_Regular_otf_start
global _binary_NotoSerifBalinese_Regular_otf_end
global _binary_NotoSerifBalinese_Regular_otf_size
_binary_NotoSerifBalinese_Regular_otf:
_binary_NotoSerifBalinese_Regular_otf_start:
    db 0
_binary_NotoSerifBalinese_Regular_otf_end:
_binary_NotoSerifBalinese_Regular_otf_size: dq 0

global _binary_NotoSerifBengali_Regular_otf
global _binary_NotoSerifBengali_Regular_otf_start
global _binary_NotoSerifBengali_Regular_otf_end
global _binary_NotoSerifBengali_Regular_otf_size
_binary_NotoSerifBengali_Regular_otf:
_binary_NotoSerifBengali_Regular_otf_start:
    db 0
_binary_NotoSerifBengali_Regular_otf_end:
_binary_NotoSerifBengali_Regular_otf_size: dq 0

global _binary_NotoSerifDevanagari_Regular_otf
global _binary_NotoSerifDevanagari_Regular_otf_start
global _binary_NotoSerifDevanagari_Regular_otf_end
global _binary_NotoSerifDevanagari_Regular_otf_size
_binary_NotoSerifDevanagari_Regular_otf:
_binary_NotoSerifDevanagari_Regular_otf_start:
    db 0
_binary_NotoSerifDevanagari_Regular_otf_end:
_binary_NotoSerifDevanagari_Regular_otf_size: dq 0

global _binary_NotoSerifDogra_Regular_otf
global _binary_NotoSerifDogra_Regular_otf_start
global _binary_NotoSerifDogra_Regular_otf_end
global _binary_NotoSerifDogra_Regular_otf_size
_binary_NotoSerifDogra_Regular_otf:
_binary_NotoSerifDogra_Regular_otf_start:
    db 0
_binary_NotoSerifDogra_Regular_otf_end:
_binary_NotoSerifDogra_Regular_otf_size: dq 0

global _binary_NotoSerifEthiopic_Regular_otf
global _binary_NotoSerifEthiopic_Regular_otf_start
global _binary_NotoSerifEthiopic_Regular_otf_end
global _binary_NotoSerifEthiopic_Regular_otf_size
_binary_NotoSerifEthiopic_Regular_otf:
_binary_NotoSerifEthiopic_Regular_otf_start:
    db 0
_binary_NotoSerifEthiopic_Regular_otf_end:
_binary_NotoSerifEthiopic_Regular_otf_size: dq 0

global _binary_NotoSerifGeorgian_Regular_otf
global _binary_NotoSerifGeorgian_Regular_otf_start
global _binary_NotoSerifGeorgian_Regular_otf_end
global _binary_NotoSerifGeorgian_Regular_otf_size
_binary_NotoSerifGeorgian_Regular_otf:
_binary_NotoSerifGeorgian_Regular_otf_start:
    db 0
_binary_NotoSerifGeorgian_Regular_otf_end:
_binary_NotoSerifGeorgian_Regular_otf_size: dq 0

global _binary_NotoSerifGrantha_Regular_otf
global _binary_NotoSerifGrantha_Regular_otf_start
global _binary_NotoSerifGrantha_Regular_otf_end
global _binary_NotoSerifGrantha_Regular_otf_size
_binary_NotoSerifGrantha_Regular_otf:
_binary_NotoSerifGrantha_Regular_otf_start:
    incbin "mupdf/resources/fonts/noto/NotoSerifGrantha-Regular.otf"
_binary_NotoSerifGrantha_Regular_otf_end:
_binary_NotoSerifGrantha_Regular_otf_size: dq _binary_NotoSerifGrantha_Regular_otf_end - _binary_NotoSerifGrantha_Regular_otf_start

global _binary_NotoSerifGujarati_Regular_otf
global _binary_NotoSerifGujarati_Regular_otf_start
global _binary_NotoSerifGujarati_Regular_otf_end
global _binary_NotoSerifGujarati_Regular_otf_size
_binary_NotoSerifGujarati_Regular_otf:
_binary_NotoSerifGujarati_Regular_otf_start:
    db 0
_binary_NotoSerifGujarati_Regular_otf_end:
_binary_NotoSerifGujarati_Regular_otf_size: dq 0

global _binary_NotoSerifGurmukhi_Regular_otf
global _binary_NotoSerifGurmukhi_Regular_otf_start
global _binary_NotoSerifGurmukhi_Regular_otf_end
global _binary_NotoSerifGurmukhi_Regular_otf_size
_binary_NotoSerifGurmukhi_Regular_otf:
_binary_NotoSerifGurmukhi_Regular_otf_start:
    db 0
_binary_NotoSerifGurmukhi_Regular_otf_end:
_binary_NotoSerifGurmukhi_Regular_otf_size: dq 0

global _binary_NotoSerifHebrew_Regular_otf
global _binary_NotoSerifHebrew_Regular_otf_start
global _binary_NotoSerifHebrew_Regular_otf_end
global _binary_NotoSerifHebrew_Regular_otf_size
_binary_NotoSerifHebrew_Regular_otf:
_binary_NotoSerifHebrew_Regular_otf_start:
    db 0
_binary_NotoSerifHebrew_Regular_otf_end:
_binary_NotoSerifHebrew_Regular_otf_size: dq 0

global _binary_NotoSerifKannada_Regular_otf
global _binary_NotoSerifKannada_Regular_otf_start
global _binary_NotoSerifKannada_Regular_otf_end
global _binary_NotoSerifKannada_Regular_otf_size
_binary_NotoSerifKannada_Regular_otf:
_binary_NotoSerifKannada_Regular_otf_start:
    db 0
_binary_NotoSerifKannada_Regular_otf_end:
_binary_NotoSerifKannada_Regular_otf_size: dq 0

global _binary_NotoSerifKhmer_Regular_otf
global _binary_NotoSerifKhmer_Regular_otf_start
global _binary_NotoSerifKhmer_Regular_otf_end
global _binary_NotoSerifKhmer_Regular_otf_size
_binary_NotoSerifKhmer_Regular_otf:
_binary_NotoSerifKhmer_Regular_otf_start:
    db 0
_binary_NotoSerifKhmer_Regular_otf_end:
_binary_NotoSerifKhmer_Regular_otf_size: dq 0

global _binary_NotoSerifKhojki_Regular_otf
global _binary_NotoSerifKhojki_Regular_otf_start
global _binary_NotoSerifKhojki_Regular_otf_end
global _binary_NotoSerifKhojki_Regular_otf_size
_binary_NotoSerifKhojki_Regular_otf:
_binary_NotoSerifKhojki_Regular_otf_start:
    db 0
_binary_NotoSerifKhojki_Regular_otf_end:
_binary_NotoSerifKhojki_Regular_otf_size: dq 0

global _binary_NotoSerifLao_Regular_otf
global _binary_NotoSerifLao_Regular_otf_start
global _binary_NotoSerifLao_Regular_otf_end
global _binary_NotoSerifLao_Regular_otf_size
_binary_NotoSerifLao_Regular_otf:
_binary_NotoSerifLao_Regular_otf_start:
    db 0
_binary_NotoSerifLao_Regular_otf_end:
_binary_NotoSerifLao_Regular_otf_size: dq 0

global _binary_NotoSerifMalayalam_Regular_otf
global _binary_NotoSerifMalayalam_Regular_otf_start
global _binary_NotoSerifMalayalam_Regular_otf_end
global _binary_NotoSerifMalayalam_Regular_otf_size
_binary_NotoSerifMalayalam_Regular_otf:
_binary_NotoSerifMalayalam_Regular_otf_start:
    db 0
_binary_NotoSerifMalayalam_Regular_otf_end:
_binary_NotoSerifMalayalam_Regular_otf_size: dq 0

global _binary_NotoSerifMyanmar_Regular_otf
global _binary_NotoSerifMyanmar_Regular_otf_start
global _binary_NotoSerifMyanmar_Regular_otf_end
global _binary_NotoSerifMyanmar_Regular_otf_size
_binary_NotoSerifMyanmar_Regular_otf:
_binary_NotoSerifMyanmar_Regular_otf_start:
    db 0
_binary_NotoSerifMyanmar_Regular_otf_end:
_binary_NotoSerifMyanmar_Regular_otf_size: dq 0

global _binary_NotoSerifNyiakengPuachueHmong_Regular_otf
global _binary_NotoSerifNyiakengPuachueHmong_Regular_otf_start
global _binary_NotoSerifNyiakengPuachueHmong_Regular_otf_end
global _binary_NotoSerifNyiakengPuachueHmong_Regular_otf_size
_binary_NotoSerifNyiakengPuachueHmong_Regular_otf:
_binary_NotoSerifNyiakengPuachueHmong_Regular_otf_start:
    db 0
_binary_NotoSerifNyiakengPuachueHmong_Regular_otf_end:
_binary_NotoSerifNyiakengPuachueHmong_Regular_otf_size: dq 0

global _binary_NotoSerifSinhala_Regular_otf
global _binary_NotoSerifSinhala_Regular_otf_start
global _binary_NotoSerifSinhala_Regular_otf_end
global _binary_NotoSerifSinhala_Regular_otf_size
_binary_NotoSerifSinhala_Regular_otf:
_binary_NotoSerifSinhala_Regular_otf_start:
    db 0
_binary_NotoSerifSinhala_Regular_otf_end:
_binary_NotoSerifSinhala_Regular_otf_size: dq 0

global _binary_NotoSerifTamil_Regular_otf
global _binary_NotoSerifTamil_Regular_otf_start
global _binary_NotoSerifTamil_Regular_otf_end
global _binary_NotoSerifTamil_Regular_otf_size
_binary_NotoSerifTamil_Regular_otf:
_binary_NotoSerifTamil_Regular_otf_start:
    db 0
_binary_NotoSerifTamil_Regular_otf_end:
_binary_NotoSerifTamil_Regular_otf_size: dq 0

global _binary_NotoSerifTangut_Regular_otf
global _binary_NotoSerifTangut_Regular_otf_start
global _binary_NotoSerifTangut_Regular_otf_end
global _binary_NotoSerifTangut_Regular_otf_size
_binary_NotoSerifTangut_Regular_otf:
_binary_NotoSerifTangut_Regular_otf_start:
    db 0
_binary_NotoSerifTangut_Regular_otf_end:
_binary_NotoSerifTangut_Regular_otf_size: dq 0

global _binary_NotoSerifTelugu_Regular_otf
global _binary_NotoSerifTelugu_Regular_otf_start
global _binary_NotoSerifTelugu_Regular_otf_end
global _binary_NotoSerifTelugu_Regular_otf_size
_binary_NotoSerifTelugu_Regular_otf:
_binary_NotoSerifTelugu_Regular_otf_start:
    db 0
_binary_NotoSerifTelugu_Regular_otf_end:
_binary_NotoSerifTelugu_Regular_otf_size: dq 0

global _binary_NotoSerifThai_Regular_otf
global _binary_NotoSerifThai_Regular_otf_start
global _binary_NotoSerifThai_Regular_otf_end
global _binary_NotoSerifThai_Regular_otf_size
_binary_NotoSerifThai_Regular_otf:
_binary_NotoSerifThai_Regular_otf_start:
    db 0
_binary_NotoSerifThai_Regular_otf_end:
_binary_NotoSerifThai_Regular_otf_size: dq 0

global _binary_NotoSerifTibetan_Regular_otf
global _binary_NotoSerifTibetan_Regular_otf_start
global _binary_NotoSerifTibetan_Regular_otf_end
global _binary_NotoSerifTibetan_Regular_otf_size
_binary_NotoSerifTibetan_Regular_otf:
_binary_NotoSerifTibetan_Regular_otf_start:
    db 0
_binary_NotoSerifTibetan_Regular_otf_end:
_binary_NotoSerifTibetan_Regular_otf_size: dq 0

global _binary_NotoSerifYezidi_Regular_otf
global _binary_NotoSerifYezidi_Regular_otf_start
global _binary_NotoSerifYezidi_Regular_otf_end
global _binary_NotoSerifYezidi_Regular_otf_size
_binary_NotoSerifYezidi_Regular_otf:
_binary_NotoSerifYezidi_Regular_otf_start:
    db 0
_binary_NotoSerifYezidi_Regular_otf_end:
_binary_NotoSerifYezidi_Regular_otf_size: dq 0

global _binary_NotoSerif_Regular_otf
global _binary_NotoSerif_Regular_otf_start
global _binary_NotoSerif_Regular_otf_end
global _binary_NotoSerif_Regular_otf_size
_binary_NotoSerif_Regular_otf:
_binary_NotoSerif_Regular_otf_start:
    db 0
_binary_NotoSerif_Regular_otf_end:
_binary_NotoSerif_Regular_otf_size: dq 0

global _binary_SourceHanSerif_Regular_ttc
global _binary_SourceHanSerif_Regular_ttc_start
global _binary_SourceHanSerif_Regular_ttc_end
global _binary_SourceHanSerif_Regular_ttc_size
_binary_SourceHanSerif_Regular_ttc:
_binary_SourceHanSerif_Regular_ttc_start:
    incbin "mupdf/resources/fonts/han/SourceHanSerif-Regular.ttc"
_binary_SourceHanSerif_Regular_ttc_end:
_binary_SourceHanSerif_Regular_ttc_size: dq _binary_SourceHanSerif_Regular_ttc_end - _binary_SourceHanSerif_Regular_ttc_start

global _binary_StandardSymbolsPS_cff
global _binary_StandardSymbolsPS_cff_start
global _binary_StandardSymbolsPS_cff_end
global _binary_StandardSymbolsPS_cff_size
_binary_StandardSymbolsPS_cff:
_binary_StandardSymbolsPS_cff_start:
    db 0
_binary_StandardSymbolsPS_cff_end:
_binary_StandardSymbolsPS_cff_size: dq 0

global _binary_NotoSerifGranth_Regular_ttc
global _binary_NotoSerifGranth_Regular_ttc_start
global _binary_NotoSerifGranth_Regular_ttc_end
global _binary_NotoSerifGranth_Regular_ttc_size
_binary_NotoSerifGranth_Regular_ttc:
_binary_NotoSerifGranth_Regular_ttc_start:
    incbin "mupdf/resources/fonts/noto/NotoSerifGrantha-Regular.otf"
_binary_NotoSerifGranth_Regular_ttc_end:
_binary_NotoSerifGranth_Regular_ttc_size: dq _binary_NotoSerifGranth_Regular_ttc_end - _binary_NotoSerifGranth_Regular_ttc_start

