#ifndef LWIP_LWIPOPTS_H
#define LWIP_LWIPOPTS_H

#define NO_SYS 0 
#define LWIP_SOCKET 1
#define LWIP_NETCONN 1
#define LWIP_COMPAT_SOCKETS 1
#define LWIP_POSIX_SOCKETS_IO_NAMES 1

#define LWIP_IPV4 1
#define LWIP_IPV6 0

#define LWIP_ARP 1
#define LWIP_ICMP 1
#define LWIP_DHCP 1
#define LWIP_DNS 1

#define LWIP_TCP_KEEPALIVE 1
#define LWIP_WND_SCALE 1
#define TCP_RCV_SCALE 2
#define TCP_WND (8192 * 2)

#define MEM_SIZE 131072
#define MEMP_NUM_TCP_PCB 16
#define MEMP_NUM_TCP_PCB_LISTEN 8
#define MEMP_NUM_TCP_SEG 256
#define PBUF_POOL_SIZE 256

#define LWIP_PROVIDE_ERRNO 1

#define TCPIP_MBOX_SIZE 64
#define DEFAULT_RAW_RECVMBOX_SIZE 64
#define DEFAULT_UDP_RECVMBOX_SIZE 64
#define DEFAULT_TCP_RECVMBOX_SIZE 64
#define DEFAULT_ACCEPTMBOX_SIZE 64

#define TCPIP_THREAD_STACKSIZE 8192
#define TCPIP_THREAD_PRIO 1
#define DEFAULT_THREAD_STACKSIZE 8192

#endif /* LWIP_LWIPOPTS_H */
